#! /bin/bash                                                                                                                                                    

echo  "$(find -name 'a*')" "$(find -name '*z')" "$(find -name 'z*a!')"  | cut -d'/' -f4-

