#! /bin/bash                                                                                                                                                    

echo  "$(find -name 'a*')" "$(find -name '*z')" "$(find -name 'z*a!')" | xargs -n 1 basename 

